// Code generated by protoc-gen-go.
// source: areainfo.proto
// DO NOT EDIT!

package cwarea

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type AreaInfo struct {
	Code             *string `protobuf:"bytes,1,req,name=code" json:"code,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Fullname         *string `protobuf:"bytes,3,opt,name=fullname" json:"fullname,omitempty"`
	Code1            *string `protobuf:"bytes,4,opt,name=code1" json:"code1,omitempty"`
	Code2            *string `protobuf:"bytes,5,opt,name=code2" json:"code2,omitempty"`
	Code3            *string `protobuf:"bytes,6,opt,name=code3" json:"code3,omitempty"`
	Code4            *string `protobuf:"bytes,7,opt,name=code4" json:"code4,omitempty"`
	Code5            *string `protobuf:"bytes,8,opt,name=code5" json:"code5,omitempty"`
	Level            *string `protobuf:"bytes,9,opt,name=level" json:"level,omitempty"`
	Levelname        *string `protobuf:"bytes,10,opt,name=levelname" json:"levelname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AreaInfo) Reset()         { *m = AreaInfo{} }
func (m *AreaInfo) String() string { return proto.CompactTextString(m) }
func (*AreaInfo) ProtoMessage()    {}

func (m *AreaInfo) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *AreaInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *AreaInfo) GetFullname() string {
	if m != nil && m.Fullname != nil {
		return *m.Fullname
	}
	return ""
}

func (m *AreaInfo) GetCode1() string {
	if m != nil && m.Code1 != nil {
		return *m.Code1
	}
	return ""
}

func (m *AreaInfo) GetCode2() string {
	if m != nil && m.Code2 != nil {
		return *m.Code2
	}
	return ""
}

func (m *AreaInfo) GetCode3() string {
	if m != nil && m.Code3 != nil {
		return *m.Code3
	}
	return ""
}

func (m *AreaInfo) GetCode4() string {
	if m != nil && m.Code4 != nil {
		return *m.Code4
	}
	return ""
}

func (m *AreaInfo) GetCode5() string {
	if m != nil && m.Code5 != nil {
		return *m.Code5
	}
	return ""
}

func (m *AreaInfo) GetLevel() string {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return ""
}

func (m *AreaInfo) GetLevelname() string {
	if m != nil && m.Levelname != nil {
		return *m.Levelname
	}
	return ""
}

type SubAreaInfo struct {
	ParentArea       *AreaInfo   `protobuf:"bytes,1,opt,name=parent_area" json:"parent_area,omitempty"`
	Subareas         []*AreaInfo `protobuf:"bytes,2,rep,name=subareas" json:"subareas,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *SubAreaInfo) Reset()         { *m = SubAreaInfo{} }
func (m *SubAreaInfo) String() string { return proto.CompactTextString(m) }
func (*SubAreaInfo) ProtoMessage()    {}

func (m *SubAreaInfo) GetParentArea() *AreaInfo {
	if m != nil {
		return m.ParentArea
	}
	return nil
}

func (m *SubAreaInfo) GetSubareas() []*AreaInfo {
	if m != nil {
		return m.Subareas
	}
	return nil
}

type AllAreaInfo struct {
	Subareas         []*SubAreaInfo `protobuf:"bytes,1,rep,name=subareas" json:"subareas,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *AllAreaInfo) Reset()         { *m = AllAreaInfo{} }
func (m *AllAreaInfo) String() string { return proto.CompactTextString(m) }
func (*AllAreaInfo) ProtoMessage()    {}

func (m *AllAreaInfo) GetSubareas() []*SubAreaInfo {
	if m != nil {
		return m.Subareas
	}
	return nil
}

func init() {
}
